Laboratorios/LAB4/Archivo a reemplazar/config/routes.rb
Rails.application.routes.draw do
  
  resources :tweets
  resources :monstruos
  
  root 'tweets#default'

end

Laboratorios/LAB4/Archivo a reemplazar/app/models/monstruo.rb
class Monstruo < ApplicationRecord
  has_many :tweets, dependent: :destroy

  default_scope -> { order :nombre }
end

Laboratorios/LAB4/Archivo a reemplazar/app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :monstruo

end

Laboratorios/LAB4/Archivo a reemplazar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Laboratorios/LAB4/Archivo a reemplazar/app/controllers/monstruos_controller.rb
class MonstruosController < ApplicationController
  
  def index
  end

  def show
  end

  def edit    
  end
  
  def destroy
  end
end

Laboratorios/LAB4/Archivo a reemplazar/app/controllers/tweets_controller.rb
# encoding = utf-8
class TweetsController < ApplicationController
  
  def new
  	@tweet = Tweet.new
  end

  def default    
  end
  
  def index
  end

  def show
  end

  # -----------------
  # CREATE
  # El método create recibe params = { tweet: { monstruo_id: valor, estado: valor } }
end

Laboratorios/LAB4/Archivo a reemplazar/app/views/layouts/_header.html.erb
<header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          
          
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "logo.png", title: "Logo", class: "logo" %>
            Critter
          <% end %>
        </div>
        <div class="collapse navbar-collapse">
          
        </div><!--/.nav-collapse -->
      </div>

    </div>
  </header>

Laboratorios/LAB4/Archivo a reemplazar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Critter </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container"> 
  
  <% if flash[:notice] %>
    <div class="alert alert-info"> <%= flash[:notice] %> </div>
  <% end %>
  
	<%= yield %>
</div>

</body>
</html>

Laboratorios/LAB4/Archivo a reemplazar/app/views/monstruos/edit.html.erb
<h1> Editar monstruo </h1>

<p> No está hecho </p>

Laboratorios/LAB4/Archivo a reemplazar/app/views/monstruos/index.html.erb
<h1> Listado de Monstruos </h1>

<table class="table">

	<tr>
		<th> Nombre </th>
		<th> Descripción </th>
		<th> Critter start </th>
		<th> Acciones </th>
	</tr>

	<% monstruos = Monstruo.all %>
	<% monstruos.each do |monstruo| %>
		<tr>
			<td> <%= link_to monstruo.nombre, monstruo %> </td>
			<td> <%= monstruo.descripcion %> </td>
			<td> <%= (monstruo.critter_star) ? 'Si' : 'No' %> </td>
			<td>
				<%= link_to "Editar", edit_monstruo_path(monstruo), class: 'btn btn-info btn-sm' %>
				<%= link_to "Eliminar", monstruo, method: :delete, class: 'btn btn-danger btn-sm' %>
			</td>
		</tr>
	<% end %>

	<% if monstruos.size == 0 %>
		<tr> <td colspan="3"> No hay monstruos </td> </tr>
	<% end %>

</table>

Laboratorios/LAB4/Archivo a reemplazar/app/views/monstruos/show.html.erb
Ver un monstruo <br>
/app/views/monstruos/show.html.erb

Laboratorios/LAB4/Archivo a reemplazar/app/views/monstruos/ver.html.erb
<!------------------------------------------------------ 
Debe mostrarse la información del primer monstruo sin
usar el id.
Se debe mostrar el nombre (como título) y la descripción 
(como párrafo).
------------------------------------------------------>

HACER <br>
/app/views/monstruos/ver.html.erb

Laboratorios/LAB4/Archivo a reemplazar/app/views/tweets/default.html.erb
<h1> Bienvenido a Critter </h1>
<h3> ¿Qué desea hacer? </h3>
<ul>
  <li> <%= link_to "Nuevo Tweet", new_tweet_path %></li>
  <li> <%= link_to "Listado de Monstruos", monstruos_path %></li>  
</ul>

Laboratorios/LAB4/Archivo a reemplazar/app/views/tweets/index.html.erb
<!-- Listado de tweets -->

Laboratorios/LAB4/Archivo a reemplazar/app/views/tweets/new.html.erb
<div class="container">
	<h1> Crear un tweet para un monstruo </h1>

	<%= form_for @tweet do |f| %>
		
		<div class="row">
			<div class="col-md-4">
				<%= f.label :monstruo_id, 'Monstruo' %>
  				<%= collection_select(:tweet, :monstruo_id, Monstruo.all, :id, :nombre, {}, { class: 'form-control'}) %>
  			</div>
  		</div>


		<div class="row">
			<div class="col-md-6">
				<%= f.label :estado %>
  				<%= f.text_area :estado, class: 'form-control', label: 'Estado', placeholder: 'Ingrese el estado' %>
  			</div>
  		</div>

  		<%= f.submit "Crear tweet", class: 'btn btn-primary' %>
  	</div>
<% end %>
</div>

Laboratorios/LAB4/Archivo a reemplazar/app/views/tweets/show.html.erb
<!-- Ver un tweet -->
Detalle del tweet